export type Difficulty = 'Basic' | 'Moderate' | 'Advanced';

export interface Scenario {
    id: string;
    title: string;
    difficulty: Difficulty;
    context: string;
    employeeName: string;
    employeeRole: string;
    issue: string;
    personaTraits: string;
}

export const SCENARIOS: Scenario[] = [
    {
        id: '1',
        title: 'Missed Deadlines',
        difficulty: 'Basic',
        context: 'You are the engineering manager. The project is two weeks behind schedule.',
        employeeName: 'Jordan',
        employeeRole: 'Software Engineer',
        issue: 'Jordan has missed the last two sprint deadlines without communicating beforehand.',
        personaTraits: 'Generally reliable but currently overwhelmed. Avoids conflict. Will apologize readily.',
    },
    {
        id: '2',
        title: 'Code Quality Issues',
        difficulty: 'Basic',
        context: 'You are the tech lead. The team is complaining about bugs in recent features.',
        employeeName: 'Alex',
        employeeRole: 'Junior Developer',
        issue: 'Alex is merging code without sufficient testing, causing regressions.',
        personaTraits: 'Eager to please but lacks attention to detail. Needs clear, specific guidance.',
    },
    {
        id: '3',
        title: 'Resistance to New Process',
        difficulty: 'Moderate',
        context: 'You are the team lead. The company has adopted a new project management tool.',
        employeeName: 'Casey',
        employeeRole: 'Senior Designer',
        issue: 'Casey refuses to use the new tool, claiming it slows them down, and is tracking work in a spreadsheet instead.',
        personaTraits: 'Opinionated, values efficiency. Skeptical of "management fads". Needs to understand the "why".',
    },
    {
        id: '4',
        title: 'Interpersonal Conflict',
        difficulty: 'Moderate',
        context: 'You are the department head. Two of your direct reports are not getting along.',
        employeeName: 'Taylor',
        employeeRole: 'Product Manager',
        issue: 'Taylor was rude to a developer in the standup meeting, calling their idea "stupid".',
        personaTraits: 'High performer but abrasive. Thinks they are just being "honest". Defensiveness is likely.',
    },
    {
        id: '5',
        title: 'Scope Creep',
        difficulty: 'Advanced',
        context: 'You are the project manager. The client is asking for more features.',
        employeeName: 'Morgan',
        employeeRole: 'Account Manager',
        issue: 'Morgan keeps promising new features to the client without consulting the dev team, causing burnout.',
        personaTraits: 'Charming, sales-focused. Feels the dev team is "too slow" and "blockers". Will try to charm their way out of it or blame the client.',
    },
    {
        id: '6',
        title: 'Chronic Lateness',
        difficulty: 'Advanced',
        context: 'You are the operations manager. Shift start times are critical.',
        employeeName: 'Riley',
        employeeRole: 'Support Specialist',
        issue: 'Riley has been late 3 times this week. They have a valid personal reason but it is impacting the team.',
        personaTraits: 'Stressed, defensive about personal life. Feels the policy is too rigid. May cry or get angry if pushed too hard.',
    },
    {
        id: '7',
        title: 'Frequent Interruptions',
        difficulty: 'Basic',
        context: 'You are the engineering manager. Focus time has been a team priority this quarter.',
        employeeName: 'Sam',
        employeeRole: 'Backend Developer',
        issue: 'Sam frequently interrupts teammates during pairing sessions and meetings, making others feel unheard.',
        personaTraits: 'Enthusiastic and talkative. Believes they are being helpful. Responds well to specific examples.',
    },
    {
        id: '8',
        title: 'Missed Documentation',
        difficulty: 'Basic',
        context: 'You are the documentation lead. The team relies on consistent runbooks.',
        employeeName: 'Priya',
        employeeRole: 'Infrastructure Engineer',
        issue: 'Priya ships changes without updating runbooks, causing confusion during on-call rotations.',
        personaTraits: 'Fast-moving, dislikes writing. Wants to be helpful but underestimates the impact of missing docs.',
    },
    {
        id: '9',
        title: 'Unclear Ownership',
        difficulty: 'Basic',
        context: 'You are the product manager. A key initiative is stalled.',
        employeeName: 'Leo',
        employeeRole: 'Data Analyst',
        issue: 'Leo is working on multiple projects but is not committing to deadlines or clarifying deliverables.',
        personaTraits: 'Agreeable, avoids confrontation. Needs help prioritizing and setting boundaries.',
    },
    {
        id: '10',
        title: 'Negative Attitude',
        difficulty: 'Basic',
        context: 'You are the team lead. Morale has dipped recently.',
        employeeName: 'Avery',
        employeeRole: 'QA Engineer',
        issue: 'Avery rolls their eyes in meetings and makes sarcastic comments about leadership decisions.',
        personaTraits: 'Cynical, witty. Values authenticity. May respond better to empathy than directives.',
    },
    {
        id: '11',
        title: 'Micromanagement',
        difficulty: 'Moderate',
        context: 'You are the department head. Direct reports have raised concerns.',
        employeeName: 'Jamie',
        employeeRole: 'Team Lead',
        issue: 'Jamie is checking in on tasks multiple times per day and rewriting team members’ work.',
        personaTraits: 'Perfectionist, anxious about quality. Believes close oversight is necessary. Defensive about intent.',
    },
    {
        id: '12',
        title: 'Skipped 1:1s',
        difficulty: 'Moderate',
        context: 'You are the engineering manager. Career conversations have lagged.',
        employeeName: 'Nia',
        employeeRole: 'Technical Lead',
        issue: 'Nia frequently cancels 1:1s with their team to handle urgent work, leaving direct reports feeling unsupported.',
        personaTraits: 'Goal-oriented, pragmatic. Values efficiency. Believes people are fine if not complaining.',
    },
    {
        id: '13',
        title: 'Overcommitting',
        difficulty: 'Moderate',
        context: 'You are the project manager. Quarterly planning is at risk.',
        employeeName: 'Diego',
        employeeRole: 'Front-end Developer',
        issue: 'Diego keeps saying yes to additional tasks, then delivers late or not at all.',
        personaTraits: 'People-pleaser, wants recognition. Has difficulty saying no. Embarrassed about delays.',
    },
    {
        id: '14',
        title: 'Unresponsive During On-Call',
        difficulty: 'Moderate',
        context: 'You are the SRE manager. Incident response times have increased.',
        employeeName: 'Harper',
        employeeRole: 'Site Reliability Engineer',
        issue: 'Harper is slow to acknowledge alerts and sometimes misses handoffs at shift change.',
        personaTraits: 'Calm under pressure but disengaged with process. Values autonomy. Prefers minimal check-ins.',
    },
    {
        id: '15',
        title: 'Undermining Decisions',
        difficulty: 'Moderate',
        context: 'You are the product director. A roadmap pivot was just announced.',
        employeeName: 'Mina',
        employeeRole: 'Senior Product Manager',
        issue: 'Mina is telling stakeholders the new direction will fail and encouraging them to wait it out.',
        personaTraits: 'Analytical, skeptical. Believes they know better. Values data-driven debate.',
    },
    {
        id: '16',
        title: 'Incomplete Handoffs',
        difficulty: 'Moderate',
        context: 'You are the customer success manager. Support escalations are rising.',
        employeeName: 'Omar',
        employeeRole: 'Customer Success Manager',
        issue: 'Omar hands off complex cases without documenting steps taken, forcing others to restart from scratch.',
        personaTraits: 'Friendly, rushed. Prioritizes responsiveness over thoroughness. Responds to clear checklists.',
    },
    {
        id: '17',
        title: 'Team Silos',
        difficulty: 'Moderate',
        context: 'You are the engineering director. Collaboration between squads is suffering.',
        employeeName: 'Isabella',
        employeeRole: 'Platform Engineer',
        issue: 'Isabella keeps building bespoke solutions instead of shared components, slowing integration.',
        personaTraits: 'Independent, proud of craftsmanship. Values technical elegance over alignment.',
    },
    {
        id: '18',
        title: 'Inappropriate Jokes',
        difficulty: 'Moderate',
        context: 'You are the HR manager. A respectful culture is a priority.',
        employeeName: 'Chris',
        employeeRole: 'Support Lead',
        issue: 'Chris made offhand jokes in chat that some teammates found offensive.',
        personaTraits: 'Sees humor as bonding. Dismissive of “overreactions.” May need clarity on impact and expectations.',
    },
    {
        id: '19',
        title: 'Slow Decision-Making',
        difficulty: 'Moderate',
        context: 'You are the data science manager. A/B tests are backing up.',
        employeeName: 'Quinn',
        employeeRole: 'Data Scientist',
        issue: 'Quinn delays launching experiments waiting for perfect confidence, blocking product learning.',
        personaTraits: 'Methodical, risk-averse. Values rigor. Needs clarity on acceptable risk and timelines.',
    },
    {
        id: '20',
        title: 'Remote Communication Gaps',
        difficulty: 'Moderate',
        context: 'You are the distributed team manager. Collaboration is async.',
        employeeName: 'Lin',
        employeeRole: 'Full-Stack Developer',
        issue: 'Lin rarely updates tickets or Slack, leaving teammates guessing about progress.',
        personaTraits: 'Introverted, prefers deep work. Feels status updates are performative. Responds to structured routines.',
    },
    {
        id: '21',
        title: 'Scope vs Quality Tradeoff',
        difficulty: 'Advanced',
        context: 'You are the engineering manager. A deadline is immovable.',
        employeeName: 'Renee',
        employeeRole: 'Staff Engineer',
        issue: 'Renee keeps expanding the scope to improve quality, threatening the launch date.',
        personaTraits: 'Craftsmanship-oriented, respected. Values technical excellence. Motivated by user impact.',
    },
    {
        id: '22',
        title: 'Escalating Burnout',
        difficulty: 'Advanced',
        context: 'You are the director. The team has been through a rough quarter.',
        employeeName: 'Marcus',
        employeeRole: 'Engineering Manager',
        issue: 'Marcus is working nights and weekends, refusing to delegate, and showing signs of burnout.',
        personaTraits: 'Protective of team, self-sacrificing. Hard time asking for help. Worries about perception.',
    },
    {
        id: '23',
        title: 'Policy Non-Compliance',
        difficulty: 'Advanced',
        context: 'You are the security lead. Compliance requirements are strict.',
        employeeName: 'Dana',
        employeeRole: 'Mobile Developer',
        issue: 'Dana bypassed security reviews to ship a hotfix, risking audit violations.',
        personaTraits: 'Pragmatic, dislikes bureaucracy. Proud of speed. Needs to see business impact of compliance.',
    },
    {
        id: '24',
        title: 'Dominating Meetings',
        difficulty: 'Advanced',
        context: 'You are the CTO. Executive design reviews need balanced input.',
        employeeName: 'Elliot',
        employeeRole: 'Principal Architect',
        issue: 'Elliot monopolizes discussion, dismissing others’ ideas and pushing their own design.',
        personaTraits: 'Confident, status-driven. Sees debate as competition. Respects data and peer feedback.',
    },
    {
        id: '25',
        title: 'Peer Conflict Over Credit',
        difficulty: 'Advanced',
        context: 'You are the VP of Engineering. Two senior engineers disagree over recognition.',
        employeeName: 'Tasha',
        employeeRole: 'Senior Engineer',
        issue: 'Tasha believes a colleague is taking credit for their work and is escalating tension.',
        personaTraits: 'High achiever, sensitive to fairness. Values transparency and public acknowledgment.',
    },
    {
        id: '26',
        title: 'Lack of Career Growth Plan',
        difficulty: 'Advanced',
        context: 'You are the director. Promotions are coming up.',
        employeeName: 'Viktor',
        employeeRole: 'Data Engineer',
        issue: 'Viktor is frustrated about stalled growth and is considering leaving due to unclear expectations.',
        personaTraits: 'Direct, ambitious. Wants concrete milestones. Values honest feedback even if tough.',
    },
    {
        id: '27',
        title: 'Cross-Team Friction',
        difficulty: 'Advanced',
        context: 'You are the program manager. Platform and feature teams are clashing.',
        employeeName: 'Sofia',
        employeeRole: 'API Lead',
        issue: 'Sofia is blocking feature work by rejecting integration approaches without offering alternatives.',
        personaTraits: 'Protective of standards. Blunt communicator. Motivated by clear success metrics.',
    },
    {
        id: '28',
        title: 'Unethical Sales Tactics',
        difficulty: 'Advanced',
        context: 'You are the regional director. A major account is at stake.',
        employeeName: 'Brandon',
        employeeRole: 'Enterprise Account Executive',
        issue: 'Brandon hinted at undocumented features to close a deal, risking reputational damage.',
        personaTraits: 'Quota-driven, persuasive. Sees rules as flexible. Responds to consequences and incentives.',
    },
    {
        id: '29',
        title: 'Team Avoiding Feedback',
        difficulty: 'Advanced',
        context: 'You are the engineering manager. Retrospectives have become shallow.',
        employeeName: 'Helena',
        employeeRole: 'Scrum Master',
        issue: 'Helena shuts down critical feedback to keep meetings positive, preventing learning.',
        personaTraits: 'Optimistic, harmony-seeking. Dislikes conflict. Will respond to structured facilitation tools.',
    },
    {
        id: '30',
        title: 'Inconsistent Performance',
        difficulty: 'Advanced',
        context: 'You are the design director. Stakeholders are confused by uneven quality.',
        employeeName: 'Rowan',
        employeeRole: 'Product Designer',
        issue: 'Rowan produces stellar work some weeks and minimal output others without explanation.',
        personaTraits: 'Creative, moody. May have external stressors. Responds to empathetic inquiry and structure.',
    },
    {
        id: '31',
        title: 'Change Resistance After Reorg',
        difficulty: 'Advanced',
        context: 'You are the GM. A reorg merged two teams last month.',
        employeeName: 'Caleb',
        employeeRole: 'Operations Lead',
        issue: 'Caleb is openly questioning leadership choices and encouraging the old team to ignore new processes.',
        personaTraits: 'Loyal to former team, skeptical of change. Values respect and clarity about rationale.',
    },
    {
        id: '32',
        title: 'Mentorship Gaps',
        difficulty: 'Advanced',
        context: 'You are the engineering manager. New hires need support.',
        employeeName: 'Yara',
        employeeRole: 'Senior Engineer',
        issue: 'Yara prefers solo work and is not mentoring juniors assigned to pair with them.',
        personaTraits: 'Independent, introverted. Values autonomy. Responds to explicit expectations and incentives.',
    },
    {
        id: '33',
        title: 'Workplace Gossip',
        difficulty: 'Advanced',
        context: 'You are the site lead. Trust within the team is eroding.',
        employeeName: 'Noah',
        employeeRole: 'Support Supervisor',
        issue: 'Noah shares confidential information about colleagues, creating factions within the team.',
        personaTraits: 'Social connector, seeks influence. May downplay harm. Needs firm boundaries and consequences.',
    },
    {
        id: '34',
        title: 'Quality vs Velocity Debate',
        difficulty: 'Advanced',
        context: 'You are the VP of Product. Leadership disagrees on priorities.',
        employeeName: 'Imani',
        employeeRole: 'Head of Engineering',
        issue: 'Imani is pushing to slow all releases for refactors, clashing with go-to-market commitments.',
        personaTraits: 'Strategic, protective of engineers. Influenced by data and customer outcomes.',
    },
    {
        id: '35',
        title: 'Allyship and Inclusion',
        difficulty: 'Advanced',
        context: 'You are the HR director. ERG feedback highlights gaps.',
        employeeName: 'Lena',
        employeeRole: 'People Manager',
        issue: 'Lena minimizes reports of microaggressions on her team and delays addressing concerns.',
        personaTraits: 'Wants to be seen as fair. Uncomfortable with conflict. Responds to clear expectations and training.',
    },
    {
        id: '36',
        title: 'Budget Overruns',
        difficulty: 'Advanced',
        context: 'You are the finance manager. Department budgets are tight.',
        employeeName: 'Gina',
        employeeRole: 'Project Manager',
        issue: 'Gina keeps approving contractor extensions without approval, creating budget overruns.',
        personaTraits: 'Solution-oriented, dislikes delays. Believes results justify spend. Needs guardrails and escalation paths.',
    },
];

export function getRandomScenario(difficulty: Difficulty | 'Random'): Scenario {
    let pool = SCENARIOS;
    if (difficulty !== 'Random') {
        pool = SCENARIOS.filter((s) => s.difficulty === difficulty);
    }

    // Fallback if pool is empty (shouldn't happen with default data)
    if (pool.length === 0) pool = SCENARIOS;

    const randomIndex = Math.floor(Math.random() * pool.length);
    return pool[randomIndex];
}
